services:
  db:
    image: mariadb:latest
    container_name: esnapp_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: esnapp
      MYSQL_USER: esnappuser
      MYSQL_PASSWORD: esnappuserpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - esnapp_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: esnapp_backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: esnappuser
      DB_PASSWORD: esnappuserpassword
      DB_NAME: esnapp
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - esnapp_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: esnapp_frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3001:3000'
    networks:
      - esnapp_network

volumes:
  db_data:

networks:
  esnapp_network:
    driver: bridge
