name: Build and Deploy

on:
  workflow_call:  # This allows the workflow to be called by other workflows

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env file
        run: |
          cat << EOF > .env
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE=${{ env.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          
          SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/${{ env.MYSQL_DATABASE }}
          SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_USER }}
          SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          SPRING_JPA_HIBERNATE_DDL_AUTO=validate
          SPRING_JPA_SHOW_SQL=false
          SPRING_JPA_FORMAT_SQL=false
          
          DOMAIN_FRONTEND=${{ env.DOMAIN_FRONTEND }}
          DOMAIN_BACKEND=${{ env.DOMAIN_BACKEND }}
          DOMAIN_ADMINER=${{ env.DOMAIN_ADMINER }}
          EOF

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
          build-args: |
            SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/${{ env.MYSQL_DATABASE }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_USER }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
          build-args: |
            API_URL=https://${{ env.DOMAIN_BACKEND }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cat << EOF > ~/consultant-tracking/.env
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE=${{ env.MYSQL_DATABASE }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            
            SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/${{ env.MYSQL_DATABASE }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_USER }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            SPRING_JPA_HIBERNATE_DDL_AUTO=validate
            SPRING_JPA_SHOW_SQL=false
            SPRING_JPA_FORMAT_SQL=false
            
            DOMAIN_FRONTEND=${{ env.DOMAIN_FRONTEND }}
            DOMAIN_BACKEND=${{ env.DOMAIN_BACKEND }}
            DOMAIN_ADMINER=${{ env.DOMAIN_ADMINER }}
            EOF
